### ISSUE TITLE
This repo is amazing!

### ISSUE THREAD

**Issue by RasmusToivanen** [NathanUA/U-2-Net#109]
I am in the works of doing a web site that has this running in AWS lambda. Front is really simple with Vue.js, upload image --> send to backend --> get it back after this transformation . I have it 100% working locally with Flask and most of the problems with AWS Lambda are solved.

I will post here a link to the website once I am ready (Hopefully this week)

![image](https://user-images.githubusercontent.com/69349765/100607475-a9bc0980-3313-11eb-8ef6-62e009b71283.png)

**Comment by NathanUA** [comment]
Great job, Rasmus.

**Comment by NathanUA** [comment]
We are also trying to provide a online demo.

**Comment by NathanUA** [comment]
Great job, Rasmus. We are also trying provide a online demo. Currently, we are still trying to improve the performance.

**Comment by JiangBing123** [comment]
This is the first salient-object-detection algorithm I used in my work. I was surprised by wonderful segmentation results!!! Amazing work!!!

**Comment by RasmusToivanen** [comment]
I hit barrier earlier with 3 GB memory limit / 30 sec timeout limit with AWS API GW but in december AWS Lambda incereased max memory in Lambda to 10 GB. I tested it yesterday and now it performs under 30 sec with 3,5 GB of used memory. Still few issues to fix but I think I finally can make it work

**Comment by R4ZZ3** [comment]
Got it working. Will set up hosting to AWS tomorrow or during the weekend
![image](https://user-images.githubusercontent.com/25264037/103952546-43fc4200-5149-11eb-96d9-af2e525439a5.png)

**Comment by R4ZZ3** [comment]
I have it now running here --> http://s3-website-hosting-u2net.s3-website-eu-west-1.amazonaws.com/
It is now limited to 1000 requests per month. Also no pinging to keep lambdas hot is yet done and cold start takes like 1 minute or so but I will probably keep on working on this to have at least 1 lambda hot all the time @NathanUA

**Comment by RasmusToivanen** [comment]
Closing for now @NathanUA

**Comment by R4ZZ3** [comment]
Somewhat disapointed now to see that there is now demo available and my demo wasn't given any comments or credit. I quess I pinged wrong person fml @xuebinqin 
![image](https://user-images.githubusercontent.com/25264037/109673761-03380c80-7b7f-11eb-91f7-3935aad5d7e7.png)

![Uploading image.png…]()

**Comment by xuebinqin** [comment]
Sorry @R4ZZ3 , I remember that you pinged before. But I tested it and wait for a long time there was no results out, so I thought your demo wasn't ready yet. It is worth to note that we don't want to grap any others' credits. Just like we describe others work like" Xiaolong Liu developed several very interesting applications based on U^2-Net including Human Portrait Drawing(As far as I know, Xiaolong is the first one who uses U^2-Net for portrait generation), image matting and so on." Xiaolong Liu is the first one who builds the online demo for the segmentation, matting and portrait generation. We are happy to see that. We are trying our best to describe the contributions and credits as accurate as possible. We are also very happy to see diversified applications of our algorithm and encourage people to allow us include their links or inspiring figures in the readme to attract more attention to their repos and projects. But before that we will also check if the included links or projects really work. I double checked your online demo, it works on some small images (takes tens of seconds) but for some big images may take a few minutes or even longer. I guess the problem may because of using the free cpu server on amazon aws. Our demo  is now running on our newly configured GPU server in our lab (which takes some time to configure), that's why we just released the online demo although we have finished that a few month ago. Could you please double check your code and give us simple descriptions of your webpage ? If you want, we are also happy to include your project page  in our README and try to bring more attention to your demo. Thank you again for your interests and efforts.

**Comment by R4ZZ3** [comment]
Thanks for fast comment :)

It was running with AWS Lambda (10 GB memory and CPU scales based on configured memory) backend so the initial try takes around 1 minute and 2-3 tries to take the first one (I didn't configure those to be "hot all the time). After that it takes few seconds per image.

Your demo is great now. I would have just wanted some feedback at the time, thats all.
Goodspeed :)

**Comment by xuebinqin** [comment]
You're very welcome. We just updated our README and include more applications including your implementation. If you have any questions and concerns, please feel free to let us know. Thank you again for your works and questions.
