### ISSUE TITLE
Input Size

### ISSUE THREAD

**Issue by smonefrmsouth** [NathanUA/U-2-Net#13]
Hi Team,
Great work!!!
I have a doubt is the input size fixed with 320*320?

**Comment by NathanUA** [comment]
Theoretically, the model is able to handle different sizes. You can change 320x320 to what you want (shouldn't be too small, otherwise the pooling operation may get error then. Size with odden number may not work either, because we upsample the feature maps by factor=2 not to certain size). But the performance is not guaranteed. Because our training process are all resized to 320x320.

**Comment by smonefrmsouth** [comment]
Thanks for your reply
the model only works with inputs sizes multiple of 320.

**Comment by NathanUA** [comment]
It should also work with 288x288 and 256x256. If you want to it work with arbitrary size, you can change all the upsampling operation. Try to replace the upsampling factor with the exact expected upsampling size.

**Comment by NathanUA** [comment]
I may update the upsampling part later. Shouldn't be a big issue.

**Comment by smonefrmsouth** [comment]
ya got it!!!
