### ISSUE TITLE
关于损失函数的问题

### ISSUE THREAD

**Issue by harrywellington9588** [NathanUA/U-2-Net#145]
作者您好，想请教您为什么没有在U2net里采用Basnet里面的混合损失函数呢？如果采用bce+ssim+iou的混合损失函数效果会不会更好呢？

**Comment by NathanUA** [comment]
Losses and network architecture are sometimes dependent. For example, bce,
ssim and iou are pixel-wise, patch-wise and map-wise supervision for the
BASNet's predict-refine architecture. But the stages in U^2Net already have
the ability of extracting multi-scale information from feature maps with
different resolutions. Then the quantitative improvements of using BSI in
U^2Net in terms of the commonly used metrics (e.g. Fmeasure, mae, etc.) are
not that significant. Besides, bce+ssim+iou can produce sharp results for
those 'hard' boundaries while bce provides a better supervision on those
soft segmentation regions (e.g. hair, feather etc). These two losses can be
used for different applications. In real applications, it is hard to say
which one is better. So we decided to use bce in the U^2Net to make these
two models suitable for different scenarios as I just mentioned above.


On Jan 13, 2021, at 11:05 PM, harrywellington9588 <notifications@github.com>
wrote:


作者您好，想请教您为什么没有在U2net里采用Basnet里面的混合损失函数呢？如果采用bce+ssim+iou的混合损失函数效果会不会更好呢？

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NathanUA/U-2-Net/issues/145>, or unsubscribe

**Comment by harrywellington9588** [comment]
非常感谢，受教了
