### ISSUE TITLE
prediction confidence score?

### ISSUE THREAD

**Issue by szerintedmi** [NathanUA/U-2-Net#6]
Hi Nathan, 

  Such a great job, much better results than other nets I played with ( including my experimentations training a blank U-Net).  Thank you for making it available. 

How would you calculate some kind of "prediction confidence" score? 
It could be used during inference to flag predictions which require human review. 

   Thinking on my feet I was considering to experiment with these naive approaches:

   1. Calculate it based on how much is the deviance from 0 and 1 in predicted pixels. Does a prediction closer to 0.5 for a pixel indicates less confidence in whether the pixel is fg or bg?
   1. Calculate losses on a bunch of input images with ground truth. Then based on it train a network to predict loss on any arbitrary image.

**Comment by NathanUA** [comment]
Thanks for your interests. The prediction confidence is exactly what you mentioned in the following question (1). But we didn't explicitly compute the prediction confidence. 
(1) Yes, it does. When you compute the difference between the prediction, you will get a error map, which was minimized by the training process.
(2) It sounds like a GAN: use a network to get prediction and use another one to evaluate the the prediction quality. But for segmentation tasks, the losses should be calculated pixel-wise not image wise (keep the error map not the mean error of the error map)  because the predictions of some pixels in an image may be good others are not. I guess you want to recognized these bad predicted pixels not images.
